// URL-ovi stranica s financijskim izvještajima za svaku ZSE dionicu.
// Koristi se za scraping financijskih podataka direktno s web stranica tvrtki.

export const FINANCIAL_REPORT_URLS: Record<string, string> = {
  ACI:   'https://corporate.aci-marinas.com/financijska-izvjesca/',
  ADPL:  'https://www.adplastik.hr/investitori',
  ADRS:  'https://www.adris.hr/odnosi-s-javnoscu/odnosi-s-investitorima/financijska-izvjesca/2024-2/',
  ADRS2: 'https://www.adris.hr/odnosi-s-javnoscu/odnosi-s-investitorima/financijska-izvjesca/2024-2/',
  ARNT:  'https://www.arenahotels.com/hr/o-nama/objave/arenaturist-profile',
  ATGR:  'https://www.atlanticgrupa.com/hr/investitori/financijski-izvjestaji/',
  AUHR:  'https://www.autohrvatska.hr/dionicko-drustvo.aspx',
  CKML:  'https://cak-mlinovi.hr/financijska_godina/2024/',
  CROS:  'https://www.crosig.hr/hr/investitori/godisnja-izvjesca/',
  CROS2: 'https://www.crosig.hr/hr/investitori/godisnja-izvjesca/',
  CTKS:  'https://cateks.hr/en/news/',
  DDJH:  'https://duro-dakovic.com/en/investor-news/',
  DLKV:  'https://www.dalekovod.com/izvjesca-2013.aspx',
  ERNT:  'https://www.ericsson.hr/godisnji-izvjestaji',
  GRNL:  'https://www.granolio.hr/en/investors/',
  HPB:   'https://www.hpb.hr/hr/financijska-izvjesca-i-ostale-informacije-za-investitore/322',
  HPDG:  'https://www.hep.hr/ods/o-nama/financijska-izvjesca/660',
  HT:    'https://www.t.ht.hr/odnosi-s-investitorima/financijska-izvjesca',
  IG:    'https://www.ing-grad.hr/hr/investitori/financijska-izvjesca',
  IGH:   'https://www.igh.hr/hr/o-nama/odnosi-s-investitorima/',
  IKBA:  'https://ikb.hr/informacije/izvjesca',
  INA:   'https://www.ina.hr/en/investors/financial-reports/annual-financial-reports/',
  INGR:  'https://ingra.hr/financijski-izvjestaji/',
  JDGT:  'https://www.jadroagent.hr/hr/financijska-izvjesca/',
  JDOS:  'https://www.jadrolinija.hr/o-nama/poslovanje-jadrolinije/izvjestaj-o-poslovanju',
  JDPL:  'https://www.jadroplov.com/hr/o-drustvu/financijski-izvjestaji',
  KODT:  'https://www.koncar.hr/en/dist/dst-financial-statements',
  KODT2: 'https://www.koncar.hr/en/dist/dst-financial-statements',
  KOEI:  'https://koncar.hr/hr/tfi-pod-i-gfi-pod',
  KRAS:  'https://www.kras.hr/hr/o-nama/informacije-za-investitore/financijska-izvjesca',
  LKPC:  'https://www.luka-ploce.hr/investors/financial-report/?lang=en',
  LKRI:  'https://lukarijeka.hr/en/financial-statements/',
  MDKA:  'https://www.medika.hr/investitori/financijska-izvjesca/',
  MONP:  'http://www.monperin.hr/monperin-izvjesca.html',
  PLAG:  'https://biz.plavalaguna.hr/hr/korporativne-informacije/plava-laguna/financijska-izvjesca',
  PODR:  'https://www.podravka.hr/kompanija/investitori/financijska-izvjesca/',
  RIVP:  'https://valamar-riviera.com/hr/investitori/financijska-izvjesca/',
  SNBA:  'https://www.slatinska-banka.hr/en/banka/financijske-informacije/',
  SPAN:  'https://www.span.eu/en/investors/reports/',
  TKPR:  'https://www.tekstilpromet.hr/o-nama/financijska-izvjesca/',
  TOK:   'https://www.tokic.hr/en/investors/',
  ULPL:  'http://www.uljaniksm.com/pages/izvjesca.php',
  VLEN:  'https://www.vetropack.hr/hr/vetropack/organizacija/kljucni-pokazatelji/',
  ZABA:  'https://www.zaba.hr/home/o-nama/investitori/financijski-izvjestaji',
  ZITO:  'https://zito.hr/hr/investitori/financijska-izvjesca',
};

export function getFinancialReportUrl(ticker: string): string | null {
  return FINANCIAL_REPORT_URLS[ticker] ?? null;
}
